CREATE TABLE IF NOT EXISTS real_estate_transactions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    external_row_key VARCHAR(255) NOT NULL,
    property_match_key VARCHAR(500) NOT NULL,
    dataset_id VARCHAR(50) NOT NULL,
    property_category VARCHAR(50) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    lawd_code VARCHAR(10) NOT NULL,
    sgg_name VARCHAR(100),
    umd_name VARCHAR(100),
    jibun VARCHAR(100),
    address VARCHAR(500),
    display_name VARCHAR(255) NOT NULL,
    name_source VARCHAR(20) NOT NULL,
    area_m2 DECIMAL(12, 2) DEFAULT 0,
    area_pyeong DECIMAL(12, 2) DEFAULT 0,
    floor INT DEFAULT 0,
    build_year INT DEFAULT 0,
    deal_date DATE,
    deal_year_month CHAR(6) NOT NULL,
    trade_amount_manwon INT DEFAULT 0,
    deposit_amount_manwon INT DEFAULT 0,
    monthly_rent_manwon INT DEFAULT 0,
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    raw_json JSON,
    fetched_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_real_estate_external_row_key (external_row_key),
    INDEX idx_real_estate_match_key (property_match_key),
    INDEX idx_real_estate_month (deal_year_month),
    INDEX idx_real_estate_date (deal_date),
    INDEX idx_real_estate_name (display_name),
    INDEX idx_real_estate_category (property_category, transaction_type),
    INDEX idx_real_estate_location (lawd_code, sgg_name, umd_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS real_estate_sync_checkpoint (
    dataset_id VARCHAR(50) NOT NULL,
    lawd_code VARCHAR(10) NOT NULL,
    bootstrap_started_at DATETIME,
    last_synced_year_month CHAR(6),
    bootstrap_completed_at DATETIME,
    last_result_message VARCHAR(1000),
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (dataset_id, lawd_code),
    INDEX idx_real_estate_sync_last_month (last_synced_year_month),
    INDEX idx_real_estate_sync_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
